const Router = require('express')
const router = new Router()
const controller = require('./authController')
const authMiddleware = require('./Midleware/authMidleware')


router.post('/registration', controller.registration)
router.post('/login', controller.login)
router.get('/users', controller.getUsers)
router.get('/users/:username', controller.getCurent)
router.post('/newstud', controller.addstudent)
router.post('/newstud2', controller.addstudent2)
router.get('/newmed', controller.addMed)
router.get('/newmed2', controller.addMed2)
// router.post('/modstud/:idnp', controller.modifystudent)
router.get('/elevi', controller.getElevi)
router.get('/elevi2', controller.getElevi2)
router.get('/elev/:idnp', controller.getElev)
router.get('/elev2/:idnp', controller.getElev2)
router.get('/getclass', controller.getClass)
router.get('/getclass2', controller.getClass2)
router.get('/getclassmed', controller.getClassMed1)
router.get('/getclassmed2', controller.getClassMed2)
// router.get('/elev/:class', controller.getClass)
router.put('/modstud/:idnp', controller.postElev)
router.put('/modstud2/:idnp', controller.postElev2)
router.delete('/delstud/:idnp', controller.deleteElev)
router.delete('/delstud2/:idnp', controller.deleteElev2)
router.delete('/cleardata', controller.ClearDB)


module.exports = router